import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";

import { uploadMapImage } from "@/lib/exportImage";
import { type DocSection, type DocSpec, exportToDocs } from "@/lib/googleDocs";

/**
 * Turns a desk brief into a Google Doc.
 *
 * The narrative arrives in the desk's own format — `**Section**` markers and
 * paragraphs — so it is parsed back into real headings rather than pasted as
 * one block with asterisks in it. A researcher's export should look written,
 * not dumped.
 */

const HEADING = /^\*\*(.+?)\*\*\s*(.*)$/;

function parseNarrative(narrative: string): DocSection[] {
  const sections: DocSection[] = [];
  let current: DocSection = { paragraphs: [] };

  for (const raw of narrative.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    const match = line.match(HEADING);
    if (match) {
      if (current.heading || current.paragraphs.length) sections.push(current);
      current = { heading: match[1], paragraphs: match[2] ? [match[2]] : [] };
    } else {
      current.paragraphs.push(line.replace(/\*\*/g, ""));
    }
  }
  if (current.heading || current.paragraphs.length) sections.push(current);
  return sections;
}

export async function POST(request: NextRequest) {
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const body = await request.json();
  const narrative = String(body.narrative ?? "");
  if (!narrative.trim()) {
    return NextResponse.json({ error: "narrative required" }, { status: 422 });
  }

  const rawTable = body.table as { headers?: string[]; rows?: string[][] } | undefined;
  const rawWinners = body.winners as { headers?: string[]; rows?: string[][] } | undefined;
  const facts = Array.isArray(body.facts)
    ? (body.facts as { label: string; value: string }[])
        .slice(0, 6)
        .map((f) => ({ label: String(f.label), value: String(f.value) }))
    : undefined;
  const imageUrl = typeof body.mapPng === "string" ? await uploadMapImage(body.mapPng) : null;
  const spec: DocSpec = {
    title: String(body.title ?? "Autonaly briefing").slice(0, 200),
    subtitle: body.subtitle ? String(body.subtitle).slice(0, 400) : undefined,
    facts,
    imageUrl: imageUrl ?? undefined,
    sections: parseNarrative(narrative),
    table:
      rawTable?.headers?.length && rawTable.rows?.length
        ? {
            caption: String(body.tableCaption ?? "Ranked exposure"),
            headers: rawTable.headers.map(String),
            // Docs tables are for reading, not for scrolling.
            rows: rawTable.rows.slice(0, 20).map((r) => r.map(String)),
          }
        : undefined,
    winners:
      rawWinners?.headers?.length && rawWinners.rows?.length
        ? {
            caption: "Who benefits",
            headers: rawWinners.headers.map(String),
            rows: rawWinners.rows.slice(0, 10).map((r) => r.map(String)),
          }
        : undefined,
    footer: String(
      body.footer ??
        "Generated by Autonaly. Exposure figures use latest-year trade weights " +
          "(BACI/CEPII) and model first-order effects only. Informational, not advice.",
    ).slice(0, 600),
  };

  try {
    const url = await exportToDocs(userId, spec);
    return NextResponse.json({ url });
  } catch (error) {
    const message = error instanceof Error ? error.message : "export failed";
    // "not connected" is a normal state, not a server fault — the UI turns it
    // into a Connect prompt.
    const status = message.includes("not connected") ? 409 : 502;
    return NextResponse.json({ error: message }, { status });
  }
}
