import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";

import { uploadMapImage } from "@/lib/exportImage";
import { GLOSSARY } from "@/lib/glossary";
import { type DocBlock, type DocSpec, exportToDocs } from "@/lib/googleDocs";

/**
 * Turns a desk brief into a Google Doc.
 *
 * The caller supplies the scenario-specific body as ordered blocks; the server
 * owns the parts that must always be present and correct — the narrative
 * parsed back into real headings, the glossary, and the provenance footer.
 */

const HEADING = /^\*\*(.+?)\*\*\s*(.*)$/;

/** The desk writes `**Section**` markers; a researcher's export should look
 *  written, not pasted, so they become real headings. */
function narrativeBlocks(narrative: string): DocBlock[] {
  const blocks: DocBlock[] = [];
  let paragraphs: string[] = [];
  const flush = () => {
    if (paragraphs.length) blocks.push({ kind: "paragraphs", text: paragraphs });
    paragraphs = [];
  };

  for (const raw of narrative.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    const match = line.match(HEADING);
    if (match) {
      flush();
      blocks.push({ kind: "heading", text: match[1] });
      if (match[2]) paragraphs.push(match[2]);
    } else {
      paragraphs.push(line.replace(/\*\*/g, ""));
    }
  }
  flush();
  return blocks;
}

function sanitiseBlocks(input: unknown): DocBlock[] {
  if (!Array.isArray(input)) return [];
  const out: DocBlock[] = [];
  for (const raw of input.slice(0, 60)) {
    const b = raw as Record<string, unknown>;
    if (b.kind === "heading" && typeof b.text === "string") {
      out.push({ kind: "heading", text: b.text.slice(0, 200) });
    } else if (b.kind === "paragraphs" && Array.isArray(b.text)) {
      out.push({
        kind: "paragraphs",
        text: (b.text as unknown[]).slice(0, 30).map((t) => String(t).slice(0, 2000)),
        italic: Boolean(b.italic),
      });
    } else if (b.kind === "table" && Array.isArray(b.headers) && Array.isArray(b.rows)) {
      out.push({
        kind: "table",
        headers: (b.headers as unknown[]).map(String),
        rows: (b.rows as unknown[][]).slice(0, 25).map((r) => r.map(String)),
      });
    }
  }
  return out;
}

export async function POST(request: NextRequest) {
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const body = await request.json();
  const narrative = String(body.narrative ?? "");
  if (!narrative.trim()) {
    return NextResponse.json({ error: "narrative required" }, { status: 422 });
  }

  const imageUrl = typeof body.mapPng === "string" ? await uploadMapImage(body.mapPng) : null;

  const facts = Array.isArray(body.facts)
    ? (body.facts as { label: string; value: string }[]).slice(0, 8)
    : [];

  const blocks: DocBlock[] = [
    ...(facts.length
      ? ([
          { kind: "heading", text: "Key figures" },
          {
            kind: "table",
            headers: ["Measure", "Value"],
            rows: facts.map((f) => [String(f.label), String(f.value)]),
          },
        ] as DocBlock[])
      : []),
    ...narrativeBlocks(narrative),
    ...(imageUrl
      ? ([
          { kind: "heading", text: "Exposure map" },
          {
            kind: "image",
            url: imageUrl,
            caption:
              "Colour is dependency intensity; the outlined country carries the largest absolute exposure.",
          },
        ] as DocBlock[])
      : []),
    ...sanitiseBlocks(body.blocks),
  ];

  const spec: DocSpec = {
    title: String(body.title ?? "Autonaly briefing").slice(0, 200),
    subtitle: body.subtitle ? String(body.subtitle).slice(0, 400) : undefined,
    blocks,
    glossary: {
      caption: "How to read these figures",
      headers: ["Term", "What it means"],
      rows: GLOSSARY.map((g) => [g.term, g.full]),
    },
    footer: String(
      body.footer ??
        "Generated by Autonaly. Exposure figures use latest-year trade weights " +
          "(BACI/CEPII) and model first-order effects only. Informational, not advice.",
    ).slice(0, 600),
  };

  // Dry run: return the assembled document instead of writing it. Creates
  // nothing, costs nothing, and makes "what would this produce" answerable
  // without a Google account.
  if (request.nextUrl.searchParams.get("dryrun") === "1") {
    return NextResponse.json({
      title: spec.title,
      blockCount: spec.blocks.length,
      outline: spec.blocks.map((b) =>
        b.kind === "heading"
          ? `H1  ${b.text}`
          : b.kind === "table"
            ? `TBL ${b.headers.join(" | ")} (${b.rows.length} rows)`
            : b.kind === "image"
              ? `IMG ${b.url}`
              : `P   ${b.text[0]?.slice(0, 60) ?? ""}`,
      ),
      glossaryRows: spec.glossary?.rows.length ?? 0,
    });
  }

  try {
    const url = await exportToDocs(userId, spec);
    return NextResponse.json({ url });
  } catch (error) {
    const message = error instanceof Error ? error.message : "export failed";
    const status = message.includes("not connected") ? 409 : 502;
    return NextResponse.json({ error: message }, { status });
  }
}
